#include <gtest/gtest.h>
#include <moveit/collision_detection/collision_common.h>
#include <moveit/collision_detection_fcl/collision_detector_allocator_fcl.h>
#include <moveit/planning_scene/planning_scene.h>
#include <moveit/robot_model/robot_model.h>
#include <moveit/robot_model_loader/robot_model_loader.h>
#include <moveit/robot_state/robot_state.h>

#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include <ament_index_cpp/get_package_share_directory.hpp>
#include <geometry_msgs/msg/pose.hpp>
#include <moveit_msgs/msg/collision_object.hpp>
#include <rclcpp/rclcpp.hpp>
#include <shape_msgs/msg/solid_primitive.hpp>

// Auto-generated by CMake from rm65_moveit.urdf.xacro at configure time
#include "rm65_urdf.h"

namespace {

/// @brief Read entire file contents as string.
std::string readFile(const std::string& path) {
    std::ifstream f(path);
    if (!f) {
        throw std::runtime_error("Failed to open: " + path);
    }
    return {std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>()};
}

}  // namespace

class CollisionAvoidanceTest : public ::testing::Test {
protected:
    void SetUp() override {
        node_ =
            std::make_shared<rclcpp::Node>("collision_avoidance_test_node", rclcpp::NodeOptions());

        // URDF provided by CMake at configure time (rm65_urdf.h)
        std::string urdf_str(omr_controller::test::kRm65Urdf);

        // SRDF path resolved at runtime
        std::string pkg_share = ament_index_cpp::get_package_share_directory("rm65_moveit_config");
        std::string srdf_path = pkg_share + "/config/rm65.srdf";
        std::string srdf_str = readFile(srdf_path);

        robot_model_loader::RobotModelLoader::Options opt;
        opt.urdf_string_ = urdf_str;
        opt.srdf_string_ = srdf_str;
        opt.load_kinematics_solvers_ = false;  // not needed for collision only
        robot_model_loader::RobotModelLoader loader(node_, opt);
        model_ = loader.getModel();

        scene_ = std::make_shared<planning_scene::PlanningScene>(model_);
        scene_->allocateCollisionDetector(
            collision_detection::CollisionDetectorAllocatorFCL::create());
    }

    void TearDown() override {
        scene_.reset();
        model_.reset();
        node_.reset();
    }

    /// @brief Set arm joint positions (6 DOF, radians) and update FK.
    void setArmJoints(const std::vector<double>& positions) {
        moveit::core::RobotState state(model_);
        state.setToDefaultValues();
        const auto* jmg = model_->getJointModelGroup("arm_group");
        state.setJointGroupPositions(jmg, positions);
        state.update();
        scene_->setCurrentState(state);
    }

    /// @brief Add a door-panel collision object at given pose.
    ///        Door panel is a box: 2.0 x 0.05 x 0.8 metres.
    void addDoorPanel(const geometry_msgs::msg::Pose& pose) {
        moveit_msgs::msg::CollisionObject obj;
        obj.id = "door_panel";
        obj.header.frame_id = model_->getModelFrame();
        obj.operation = moveit_msgs::msg::CollisionObject::ADD;

        shape_msgs::msg::SolidPrimitive box;
        box.type = shape_msgs::msg::SolidPrimitive::BOX;
        box.dimensions = {2.0, 0.05, 0.8};
        obj.primitives.push_back(box);
        obj.primitive_poses.push_back(pose);

        scene_->processCollisionObjectMsg(obj);
    }

    /// @brief Add a door-frame collision object at given pose.
    ///        Door frame is a cylinder: height 0.8 m, radius 0.05 m.
    void addDoorFrame(const geometry_msgs::msg::Pose& pose) {
        moveit_msgs::msg::CollisionObject obj;
        obj.id = "door_frame";
        obj.header.frame_id = model_->getModelFrame();
        obj.operation = moveit_msgs::msg::CollisionObject::ADD;

        shape_msgs::msg::SolidPrimitive cyl;
        cyl.type = shape_msgs::msg::SolidPrimitive::CYLINDER;
        cyl.dimensions = {0.8, 0.05};
        obj.primitives.push_back(cyl);
        obj.primitive_poses.push_back(pose);

        scene_->processCollisionObjectMsg(obj);
    }

    /// @brief Remove all collision objects from the scene.
    void clearCollisionObjects() { scene_->removeAllCollisionObjects(); }

    rclcpp::Node::SharedPtr node_;
    planning_scene::PlanningScenePtr scene_;
    moveit::core::RobotModelPtr model_;
};

// ──── Test 1: No collision when door panel is far from arm ──────────────────

TEST_F(CollisionAvoidanceTest, NoCollisionWhenDoorPanelIsFarAway) {
    // Arm at zero joints (fully upright)
    setArmJoints({0.0, 0.0, 0.0, 0.0, 0.0, 0.0});

    // Place door panel 2 metres above the arm base — no link should reach it
    geometry_msgs::msg::Pose far_away;
    far_away.position.z = 2.0;
    far_away.orientation.w = 1.0;
    addDoorPanel(far_away);

    collision_detection::CollisionRequest req;
    collision_detection::CollisionResult res;
    scene_->checkCollision(req, res);

    EXPECT_FALSE(res.collision) << "Arm at zero joints should not collide with door panel at Z=2.0";
}

// ──── Test 2: Collision detected when door panel intersects arm ─────────────

TEST_F(CollisionAvoidanceTest, CollisionDetectedWhenDoorPanelIntersects) {
    // Same zero-joint arm position
    setArmJoints({0.0, 0.0, 0.0, 0.0, 0.0, 0.0});

    // Door panel at origin (hinge) — base_link box (0.16×0.16×0.04) at origin
    // intersects the door panel box (2.0×0.05×0.8) at origin.
    geometry_msgs::msg::Pose at_origin;
    at_origin.orientation.w = 1.0;
    addDoorPanel(at_origin);

    collision_detection::CollisionRequest req;
    collision_detection::CollisionResult res;
    scene_->checkCollision(req, res);

    EXPECT_TRUE(res.collision) << "Arm should collide with door panel centred at origin";
}

// ──── Test 3: No collision with door frame cylinder when placed at safe
//               distance ──────────────────────────────────────────────────────

TEST_F(CollisionAvoidanceTest, NoCollisionWithDoorFrameAtSafeDistance) {
    // Arm at zero joints
    setArmJoints({0.0, 0.0, 0.0, 0.0, 0.0, 0.0});

    // Door frame cylinder placed 2 metres above arm base — clear of all links
    geometry_msgs::msg::Pose far_away;
    far_away.position.z = 2.0;
    far_away.orientation.w = 1.0;
    addDoorFrame(far_away);

    collision_detection::CollisionRequest req;
    collision_detection::CollisionResult res;
    scene_->checkCollision(req, res);

    EXPECT_FALSE(res.collision) << "No collision when door frame is at Z=2.0 — arm links are below";
}

// ──── Test 3b: Collision with door frame at origin ─────────────────────────

TEST_F(CollisionAvoidanceTest, CollisionDetectedWithDoorFrameAtOrigin) {
    // Arm at zero joints
    setArmJoints({0.0, 0.0, 0.0, 0.0, 0.0, 0.0});

    // Door frame cylinder at origin (hinge) — base_link box intersects it
    geometry_msgs::msg::Pose at_origin;
    at_origin.orientation.w = 1.0;
    addDoorFrame(at_origin);

    collision_detection::CollisionRequest req;
    collision_detection::CollisionResult res;
    scene_->checkCollision(req, res);

    EXPECT_TRUE(res.collision) << "Arm should collide with door frame cylinder at origin";
}

// ──── Test 4: ACM excludes adjacent link pairs from self-collision ──────────

TEST_F(CollisionAvoidanceTest, AcmExcludesAdjacentLinkPairs) {
    // Verify that the ACM loaded from SRDF disables self-collision for all
    // adjacent link pairs.
    const auto& acm = scene_->getAllowedCollisionMatrix();

    // Adjacent pairs from SRDF: base_link↔Link1, Link1↔Link2, …
    for (const auto& pair :
         std::initializer_list<std::pair<const char*, const char*>>{{"base_link", "Link1"},
                                                                    {"Link1", "Link2"},
                                                                    {"Link2", "Link3"},
                                                                    {"Link3", "Link4"},
                                                                    {"Link4", "Link5"},
                                                                    {"Link5", "Link6"}}) {
        EXPECT_TRUE(acm.hasEntry(pair.first, pair.second))
            << pair.first << " ↔ " << pair.second << " should be disabled by ACM";
    }

    // Verify a few NON-adjacent pairs are NOT disabled
    EXPECT_FALSE(acm.hasEntry("base_link", "Link2"))
        << "base_link ↔ Link2 is non-adjacent — must NOT be in ACM";
    EXPECT_FALSE(acm.hasEntry("Link1", "Link3"))
        << "Link1 ↔ Link3 is non-adjacent — must NOT be in ACM";

    // At zero joints the arm should have no self-collision (ACM covers
    // adjacent links; non-adjacent links do not touch at this pose).
    setArmJoints({0.0, 0.0, 0.0, 0.0, 0.0, 0.0});

    collision_detection::CollisionRequest req;
    collision_detection::CollisionResult res;
    scene_->checkSelfCollision(req, res);

    EXPECT_FALSE(res.collision) << "Self-collision should be clear at zero joints "
                                << "(ACM excludes adjacent links)";
}
