[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:controller_manager]
command=bash -c "source /opt/ros/humble/setup.bash && source /ws/install/setup.bash && ros2 run controller_manager ros2_control_node"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:move_group]
command=bash -c "source /opt/ros/humble/setup.bash && source /ws/install/setup.bash && ros2 launch rm65_moveit_config move_group.launch.py use_rviz:=false launch_arm:=false"
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/move_group.log
stderr_logfile=/var/log/supervisor/move_group_err.log
user=root

[program:calib_node]
command=bash -c "source /opt/ros/humble/setup.bash && source /ws/install/setup.bash && ros2 run omr_controller calib_node"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
