task_orchestrator:
  ros__parameters:
    bt_xml_path: "pick_and_place.xml"
    bt_tick_rate: 20.0
    motor_jtc_action: "/dais_joint_trajectory_controller/follow_joint_trajectory"
    motor_joint_state_topic: "/joint_states"
    motor_joint_name: "joint_dais"
    arm_jtc_action: "/arm_cm/follow_joint_trajectory"
    joint_state_topic: "/joint_states"
    color_lower_hsv: [0, 50, 50]
    color_upper_hsv: [10, 255, 255]
