/**:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    controller_names:
      - arm_cm
      - dais_cm

    arm_cm:
      type: FollowJointTrajectory
      action_ns: /controller_manager/joint_trajectory_controller/follow_joint_trajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      action_monitor_rate: 20.0

    dais_cm:
      type: FollowJointTrajectory
      action_ns: /controller_manager/dais_joint_trajectory_controller/follow_joint_trajectory
      default: false
      joints:
        - joint_dais
      action_monitor_rate: 20.0
